name: Build and Publish .rpm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted # Use a self-hosted runner with the necessary tools installed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip ruby ruby-dev rpm
        sudo gem install --no-document fpm

    - name: Build .rpm package
      run: |
        pip3 install prometheus_client
        fpm -s dir -t rpm -n hdparm-prometheus-exporter \
            --version 1.0.0 --iteration 1 \
            --description "Prometheus exporter for hdparm disk metrics" \
            --rpm-os linux \
            --rpm-dist el8 \
            --depends python3 \
            --depends python3-pip \
            --depends hdparm \
            --depends python3-prometheus_client \
            --after-install debian/postinst \
            --after-remove debian/postrm \
            hdparm_exporter.py=/opt/hdparm_prometheus_exporter/hdparm_exporter.py \
            hdparm_exporter.service=/usr/lib/systemd/system/hdparm_exporter.service \
            hdparm_exporter.conf=/etc/prometheus_hdparm_exporter/hdparm_exporter.conf \
            debian/hdparm_exporter=/opt/hdparm_prometheus_exporter/debian/hdparm_exporter

    - name: Upload .rpm artifact
      uses: actions/upload-artifact@v4
      with:
        name: hdparm-prometheus-exporter
        path: "*.rpm"
