name: Build and Publish .rpm

on:
  push:
    tags: # Trigger on new tags (e.g., v1.0.0)
      - 'v*'

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip ruby ruby-dev rpm
        sudo gem install --no-document fpm

    - name: Build .rpm package
      run: |
        pip3 install prometheus_client
        fpm -s dir -t rpm -n hdparm-prometheus-exporter \
            --version ${{ github.ref_name }} --iteration 1 \
            --description "Prometheus exporter for hdparm disk metrics" \
            --rpm-os linux \
            --rpm-dist el8 \
            --depends python3 \
            --depends python3-pip \
            --depends hdparm \
            --depends python3-prometheus_client \
            --after-install debian/postinst \
            --after-remove debian/postrm \
            hdparm_exporter.py=/opt/hdparm_prometheus_exporter/hdparm_exporter.py \
            hdparm_exporter.service=/usr/lib/systemd/system/hdparm_exporter.service \
            hdparm_exporter.conf=/etc/prometheus_hdparm_exporter/hdparm_exporter.conf \
            debian/hdparm_exporter=/opt/hdparm_prometheus_exporter/debian/hdparm_exporter

    - name: Generate .repo file
      run: |
        REPO_URL="https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}"
        echo "[hdparm-prometheus-exporter]" > hdparm-prometheus-exporter.repo
        echo "name=hdparm-prometheus-exporter" >> hdparm-prometheus-exporter.repo
        echo "baseurl=${REPO_URL}" >> hdparm-prometheus-exporter.repo
        echo "enabled=1" >> hdparm-prometheus-exporter.repo
        echo "gpgcheck=0" >> hdparm-prometheus-exporter.repo

    - name: Create Release and Upload .rpm and .repo
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.rpm
          *.repo
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Automated release of hdparm-prometheus-exporter version ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
